### ISSUE TITLE
Couldn't compile boost version checking program

### ISSUE THREAD

**Issue by Yanzqing** [plasmodic/ecto#274]
Couldn't compile boost version checking program: Change Dir

My boost version is 1.54.0.1

**Comment by vrabaud** [comment]
can you please provide the error message ? thx

**Comment by Yanzqing** [comment]
when is follow the instruction
cd ecto
mkdir -p build
cd build
cmake ..

CMake Error at cmake/boost.cmake:47 (message):
  Couldn't compile boost version checking program: Change Dir:
  /home/yan/ROS_Nao/PCL_tabletop/ecto/build/CMakeFiles/CMakeTmp
  Run Build Command:/usr/bin/make "cmTryCompileExec1218666962/fast"

  /usr/bin/make -f CMakeFiles/cmTryCompileExec1218666962.dir/build.make
  CMakeFiles/cmTryCompileExec1218666962.dir/build

  make[1]: Entering directory
  `/home/yan/ROS_Nao/PCL_tabletop/ecto/build/CMakeFiles/CMakeTmp'

  /usr/bin/cmake -E cmake_progress_report
  /home/yan/ROS_Nao/PCL_tabletop/ecto/build/CMakeFiles/CMakeTmp/CMakeFiles 1

  Building C object
  CMakeFiles/cmTryCompileExec1218666962.dir/boost-version.c.o

  /usr/bin/cc -I -o
  CMakeFiles/cmTryCompileExec1218666962.dir/boost-version.c.o -c
  /home/yan/ROS_Nao/PCL_tabletop/ecto/cmake/boost-version.c

  cc: error: CMakeFiles/cmTryCompileExec1218666962.dir/boost-version.c.o: No
  such file or directory

  make[1]: Leaving directory
  `/home/yan/ROS_Nao/PCL_tabletop/ecto/build/CMakeFiles/CMakeTmp'

  make[1]: *** [CMakeFiles/cmTryCompileExec1218666962.dir/boost-version.c.o]
  Error 1

  make: *** [cmTryCompileExec1218666962/fast] Error 2

Call Stack (most recent call first):
  CMakeLists.txt:67 (include)

**Comment by vrabaud** [comment]
You are not following the instructions from the doc nor the ones from catkin.

**Comment by vrabaud** [comment]
sorry, closing, you need to follow catkin instructions.
