### ISSUE TITLE
ImportError: No module named ecto_main 

### ISSUE THREAD

**Issue by jamiephillips0000** [plasmodic/ecto#286]
Hi
I encountered a problem trying to install OpenDroneMap https://github.com/OpenDroneMap/OpenDroneMap/issues/337
Error output is as follows
`ImportError: No module named ecto_main`

I chatted with @dakotabenjamin and agreed to ask you guys

To reproduce this just run the file `python/ecto/test.py`
Any help is appreciated
Kr
Jamie

**Comment by dakotabenjamin** [comment]
BTW we pull from this commit https://github.com/plasmodic/ecto/commit/c6178ed0102a66cebf503a4213c27b0f60cfca69

**Comment by vrabaud** [comment]
do you guys use catkin at all ?

**Comment by jamiephillips0000** [comment]
Yup
catkin is installed using 
`sudo pip install -U catkin-pkg`

**Comment by jamiephillips0000** [comment]
Solved - this was an issue with Anaconda (which IMO cannot be used in conjunction with OpenDroneMap).

**Comment by kaygudo** [comment]
Hey guys, while installing ecto i am getting following error:
 
CMake Error at CMakeLists.txt:32 (find_package):
  By not providing "Findcatkin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "catkin", but
  CMake did not find one.

  Could not find a package configuration file provided by "catkin" with any
  of the following names:

    catkinConfig.cmake
    catkin-config.cmake

  Add the installation prefix of "catkin" to CMAKE_PREFIX_PATH or set
  "catkin_DIR" to a directory containing one of the above files.  If "catkin"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!

any suggestions?

**Comment by jamiephillips0000** [comment]
If you are using anaconda/python then try without it.

**Comment by kaygudo** [comment]
You mean by executing "python setup.py install"?

**Comment by jamiephillips0000** [comment]
Nope
Its hard to tell from your error message - but you are using Ubuntu right?
if so it is something like
``sudo apt-get install python``
I found that a lot of python stuff that requires e.g. integration with CV2
need the systems package manager install so that everything works together

**Comment by kaygudo** [comment]
But, "sudo apt-get install python " will just install python and not ecto.isn't it?

**Comment by jamiephillips0000** [comment]
i had the same error as you while installing OpenDroneMap - which has a
dependency on ecto.
I dont know what you are installing but "Ecto is a hybrid C++/Python
development framework for constructing and maintaining pipelines"
So ecto needs python (and python with the correct bindings to dependent
system libraries) so that it will work
It might help if you mentioned
1) OS
2) What you are trying to do/install
Jamie

**Comment by kaygudo** [comment]
I am trying to install ecto itself "https://github.com/plasmodic/ecto" on ubuntu, i already have python 2.7 installed.

**Comment by jamiephillips0000** [comment]
can you post the results of
``which python``

**Comment by kaygudo** [comment]
/usr/bin/python
