### ISSUE TITLE
dynamic reconfigure

### ISSUE THREAD

**Issue by ethanrublee** [plasmodic/ecto#74]
For dynamic reconfiguration of parameters we need to add some concepts to tendrils, such as...
- Non dynamic, meaning that the parameter is only checked once, in the configure method. This would mean a change in the parameter must call configure again to take effect.
- A dynamic parameter is one which the user has either registered a callback with, or capture a spore to it. This implies that changes in the parameter will be reflected at each run of the cell's process method.
- Min, Max (for numbers)
- enumeration
- Possibly string to type converter
- Odd, prime, even (for integral types)
- etc...

An idea for the interface:

``` c++
    static void declare_params(ecto::tendrils& p)
    {
      p.declare<double> ("value") << Doc("A doc str")
                                  << Default(1)
                                  << Min(0)
                                  << Max(10)
                                  << Required(true)
                                  << Dynamic(true);
    }
```

**Comment by SebastianRiedel** [comment]
Waking up an old issue here.... However, did the tags-feature described here make it into ecto in the end? I can't find it in the master branch and wonder if there is a different way now to define value constraints for parameters (e.g. min/max as in ROS's dynamic reconfigure)?

**Comment by stonier** [comment]
Not that I can see. Certainly would be useful. I don't know that the cells need the extra complexity though - for myself the situation where I'd want to constrain a parameter is rare, and is easy enough to do in a line of code inside the cell itself.

Perhaps a useful first step would be to be able to provide the information to the gui. I've been expanding the gui myself in ways to be able to provide richer information - toggles vs buttons for booleans, custom doc strings and a parameter filter for the particular instance and parameter group organisation. Still experimenting though, but min/max options would definitely be useful.

**Comment by SebastianRiedel** [comment]
I saw your changes to the gui, for which ranges would make additional sense. My use case involves automatic optimization of parameters in a parameter space and hence some specification of meaningful parameter ranges is necessary. I think the ranges could be conveniently defined when declaring cell parameters. Maybe with an additional policy flag if violations of the limits will be ignored, clipped or trigger a runtime error inside the cell. How does that sound?

Although I'd like to implement something like that, I need some time to get familiar with the Boost magic and Boost Python to make that possible.

**Comment by stonier** [comment]
Actually, most of my changes are not yet in ecto. I have them in a private repo, but I'll release them soon.

Sure, having a handle inside c++/python to do this would be great. I only suggested the gui first since that will get you 90% of the way for little effort. That last 10% of use cases/conveniences I suspect will take quite alot of effort to get right.
